Tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('',include('apiapp.urls')),
    
    path('accounts/',include('django.contrib.auth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_title = "PetsShop"
admin.site.site_header = "Administracion de la tienda"
admin.site.index_title = "Modulos de la tienda"

app/urls.py
from unicodedata import name
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('user/', user, name="user"),
    path('perfil/', perfil, name="perfil"),
    path('seguimiento/', seguimiento, name="seguimiento"),
    path('listar_seguimiento/', listar_seguimiento, name="listar_seguimiento"),
    path('compras/<id>', compras, name="compras"),
    path('carrito/<id>/', carrito, name="carrito"),
    path('agregar_producto/',agregar_producto, name="agregar_producto"),
    path('modificar_producto/<codigo>/',modificar_producto, name="modificar_producto"),
    path('modificar_user/<run>/',modificar_user, name="modificar_user"),
    path('eliminar_producto/<codigo>/', eliminar_producto, name="eliminar_producto"),
    path('eliminar_carrito/<codigo>/', eliminar_carrito, name="eliminar_carrito"),
    path('eliminar_seguimiento/<codigo>/', eliminar_seguimiento, name="eliminar_seguimiento"),
    path('eliminar_user/<run>/', eliminar_user, name="eliminar_user"),
    path('listar_producto/',listar_productos, name="listar_producto"),
    path('listar_user/',listar_user, name="listar_user"),
    path('register/', register, name = 'register'),
    path('productos-api/', productosapi, name= 'productos-api'),
    path('api-mostrar/', apimostrar, name= 'api-mostrar'),
    path('sub/', sub, name='sub'),
    
    
  


]

app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class TipoProducto (models.Model):
    tipo = models.CharField(max_length=30)

    def __str__(self):
        return self.tipo
        
    class Meta:
        db_table = 'db_tipo_producto'

class Producto(models.Model):
    codigo = models.IntegerField(null=False,primary_key=True)
    nombre = models.CharField(max_length=20)
    marca = models.CharField(max_length=20)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=20)
    stock = models.IntegerField()
    tipo = models.ForeignKey(TipoProducto, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.nombre
    
    class Meta:
        db_table = 'db_producto'

class Usuario(models.Model):
    run = models.CharField(max_length=10,primary_key=True)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    email = models.EmailField(max_length=100)
    contraseña = models.CharField(max_length=40)
    sub = models.BooleanField(default=False)
    direccion = models.CharField(max_length=150)
    imagen = models.ImageField(upload_to="usuarios", null=True)

    def __str__(self):
        return self.run

        
    class Meta:
        db_table = 'db_usuario'

class Carrito(models.Model):
    codigo = models.AutoField(null=False,primary_key=True)
    cantidad = models.IntegerField()
    producto = models.ForeignKey(Producto, on_delete= models.CASCADE)
    usuario = models.IntegerField()

    def __str__(self):
        return self.codigo
        
    class Meta:
        db_table = 'db_carrito'

class TipoPago(models.Model):
     tipopago = models.CharField(max_length=30)

     def __str__(self):
        return self.tipopago
        
     class Meta:
        db_table = 'db_tipo_pago'

class Estado(models.Model):
    estado = models.CharField(max_length=30)

    def __str__(self):
        return self.estado
        
    class Meta:
        db_table = 'db_estado'    



class Sub(models.Model):
    email = models.EmailField(null=False,primary_key=True)
    sub = models.BooleanField(default=False)
    
    def __str__(self):
        return self.sub
        
    class Meta:
        db_table = 'db_sub'    
    


class Seguimiento(models.Model):
    codigo = models.AutoField(null=False,primary_key=True)
    cantidad = models.IntegerField()
    producto = models.ForeignKey(Producto, on_delete= models.CASCADE)
    usuario = models.IntegerField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return self.codigo
        
    class Meta:
        db_table = 'db_seguimiento'    

app/templates/app/producto/agregar_producto.html
{% extends 'app/producto/baseprod.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block contenidouser %}


<div class="container" >
  <h4 class="text-center teal lighten-4" style="font-family: Arial, Helvetica, sans-serif;" > Agregar Productos</h4>
  <div class="row ">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-8 teal lighten-4 radius mt-5">
      <form action="" method="POST" class="m-5 teal-lighten-4 " enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <input type="submit" class="btn btn-success mt-5" value="Guardar">

       
      </form>
      
    </div>
    <div class="col-sm-2">
      
    </div>
  </div>
</div>
<div class="container m-5">
  

</div>


{% endblock %}
{% block css %}

{% if messages %}
                    {% for msj in messages %}
                        <script>
                            Swal.fire({
                                title: 'Guardado!',
                                text: '{{ msj }}',
                                icon: 'success',
                                showConfirmButton: false,
                                timer: 2000
                            });
                        </script>
                    {% endfor %}
                {% endif %}
{% endblock %}

app/templates/app/producto/api-mostrar.html
{% extends 'app/user/baseuser.html' %}
{% load static %}
{% block contenidouser %}

<div class="container bg-light text-center">
  <h4 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Digimon</h4>
  <div class="row text-center">

    {% for aux in listaDigimon %}

    <div class="col-md-3">
      <div class="card adapt">
        {% if aux.img %}
        <img src="{{ aux.img }}" class="card-img-top">
        {% else %}
        <img class="card-img-top" src="{% static 'app/img/baberos.jpg' %}" alt="Card image" ||>


        {% endif %}

        <div class="card-body">
          <h4 class="card-title" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"> {{aux.name }}</h4>

          <p class="card-text" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"> Level:
            {{ aux.level }}</p>
          <form action="" method="POST">


            <br>
            
          </form>

        </div>
      </div>
    </div>


    {% endfor %}
  </div>
</div>
  <!-- END DIGIMON-->



  {% endblock %}

app/templates/app/producto/baseprod.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mascotas</title>
    {% load static %}
   <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
 
  <!-- jQuery library -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>

  <!-- aqui estaba parte del link de materialized que se elimino ,debido que no permite hacer funcionar 
       el formulario -->
    <link href="{% static 'app/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="{% static 'app/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <link href="{% static 'app/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />
  

  



</head>
<body>
  

  <!-- INICIO Navbar--> 
    <nav class="nav-wraper navbar " style="min-height: 180px;">
      <div class="container-fluid"> 
        <a class="navbar-brand " href="#">
          <img src="{% static 'app/img/Logo_Mascota-removebg-preview.png' %}" alt="" width="130"> <span class="titulo-pagina">Pets Shop</span>
        </a>
        
  
        <a href="#" class="sidenav-trigger" data-target="mobile-links">
          <i class="fa-solid fa-bars"></i>
        </a>

        <ul class=" hide-on-med-and-down">
          
          <li class=""  >
            <a class="" href="{% url 'user' %}"  >Productos</a>
        </li>
          
          <li class=""  >
              <a class="" href="{% url 'sub' %}"  >¡Suscribete!</a>
          </li>
          
            <li class="nav-item">
              <a  class="nav-link "href="{% url 'carrito' user.id  %}" > Mi carrito <i class="fa-solid fa-cart-shopping"   ></i></a>
            </li>
            
          
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white  " href="#" id="navbardrop" data-toggle="dropdown">
                {% if user.is_authenticated %}
                Bienvenido: {{ user.username}}
                {% endif %}
              </a>
              {% if user.is_authenticated %}
              <div class="dropdown-menu">
                
                <a class="dropdown-item" href="{% url 'perfil' %}"><i class="fa-solid fa-house"></i> Mi Perfil </i></a>
                <a class="dropdown-item" href="{%url 'compras' user.id %}"><i class="fa-solid fa-bag-shopping"></i> Mis compras </i></a>
                <a class="dropdown-item" href="{%url 'agregar_producto' %}"> <i class="fa-solid fa-cart-plus"></i> Agregar productos </a>
                <a class="dropdown-item" href="{% url 'listar_producto' %}"> <i class="fa-solid fa-file-pen"></i> Modificar productos </a>
                <a class="dropdown-item" href="{% url 'listar_user' %}"> <i class="fa-solid fa-user-gear"></i> Modificar usuario </a>
                
                <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa-solid fa-arrow-right-from-bracket"></i> Cerrar sesión      </i></a>
	              {% else %}
                <div class="dropdown-menu">
                
                  <a class="dropdown-item" href="{% url 'login' %}"><i class="fa-solid fa-house"></i> Iniciar sesión </i></a>
	              {% endif %}
               

              </div>
            </li>
          <li class="">
              <img src="{% static 'app/img/user.png' %}"  width="70px"  alt="">

        </ul>
      </div>
    </nav>
  
    <ul class="sidenav teal lighten-4 " id="mobile-links">

   

      



      <li>
        <div class="chip">
          <img src="{% static 'app/img/user.png' %}" alt="Contact Person">
          {% if user.is_authenticated %}
          Bienvenido: {{ user.username}}
          {% endif %}
        </div>
      </li>

      <li >
        <a  class="nav-link "href="{% url 'carrito' 1 %}"> Mi carrito <i class="fa-solid fa-cart-shopping"   ></i></a>
      </li>
      <li>
        <a class="nav-link " href="{% url 'perfil'%}"><i class="fa-solid fa-house"></i> Mi Perfil </i></a>
      </li>
      <li>
        <a class="nav-link " href="{% url 'compras' user.id %}"><i class="fa-solid fa-bag-shopping"></i> Mis compras </i></a>
      </li>
      <li>
        <a class="nav-link " href="#"><i class="fa-solid fa-heart"></i> Mis favoritos </a>
      </li>
      <hr>
      <li class=""  >
        <a class="nav-link " href="">Seccion Admin</a>
    </li>
      <li>
        <a class="nav-link" href="{% url 'agregar_producto'%}"> <i class="fa-solid fa-cart-plus"></i> Agregar productos</a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'listar_producto' %}"> <i class="fa-solid fa-file-pen"></i> Modificar productos </a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'listar_user' %}"> <i class="fa-solid fa-user-gear"></i> Modificar usuario </a>
      </li>
      <hr>
      <li class=""  >
        <a class="nav-link " href="{% url 'user'%}" >Tienda</a>
    </li>
    <li>
      <a class="" href="#" data-toggle="modal" data-target="#modalSuscriptor" >¡Suscribete!</a>
    </li>
      
      
      </div>
  
      <li>
        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s6">
                <i class="material-icons prefix">search</i>
                <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
                <label for="icon_prefix2">Busqueda</label>
              </div>
            </div>
          </form>
        </div>
  
        
      </li>
      
      <li>
        <a class="nav-link "href="{% url 'index' %}"><i class="fa-solid fa-arrow-right-from-bracket"></i> Cerrar sesión </i></a>
      </li>
  
    </ul>
  </div>
    <!-- TERMINO Navbar-->
    <div id="fondo">
{% block contenidouser %}
{% endblock %}
    <!-- INICIO Productos en cartas-->
   
    
  

    
    

    <footer class="page-footer teal lighten-4 ">
      <div class="container ">
        <div class="row">
          <div class="col l6 s12">
            <img src="{% static 'app/img/Logo_Mascota-removebg-preview.png' %}" alt="" width="140">
            <p class="grey-text text-white "> Entregamos el mejor servicio de compras productos para sus mascotas. </p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Contáctanos</h5>
            <ul>
              <li>
                <a class="grey-text text-white" href="#!"><i class="fa-brands fa-instagram"></i> Instagram</a>
              </li>
              <li><a class="grey-text text-white" href="{% static 'app/https://github.com/JaimeAndresG/PGY004' %}"><i class="fa-brands fa-github"></i> GitHub</a>
              </li>
              <li><a class="grey-text text-white" href="#!"><i class="fa-brands fa-facebook"></i> Facebook</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright text-white">
        <div class="container text-center">
        © 2022 todos los derechos reservados Pets Shop
        </div>
      </div>
    </footer>
  </div>
    



    
<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'app/js/materialize.js'%}"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
   var elems = document.querySelectorAll('.sidenav');
   var instances = M.Sidenav.init(elems);
 });
</script>
<!-- Scripts -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<!--SWEETALERT-->


  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'app/js/alertas.js'%}"></script>
  {% block css %}
  {% endblock %}
  



</body>
</html>

app/templates/app/producto/listar_producto.html
{% extends 'app/producto/baseprod.html' %}
{% load static %}
{% block contenidouser %}
<div  class="container sm-xl" style="height: 500px; padding: 30px 80px 0 80px;">
 <div class="row">
    <h4 class="text-center teal lighten-4" style="font-family: Arial, Helvetica, sans-serif;" > Listar Productos</h4>
    
    <table class="table highlight table-condensed responsive-table teal lighten-4 rounded mt-4">
        <thead>
        <tr>
        <td>CODIGO</td>
        <td>NOMBRE</td>
        <td>MARCA</td>
        <td>PRECIO</td>
        <td>STOCK</td>
        <td>DESCRIPCION</td>
        <td>TIPO</td>
        <td>IMAGEN</td>
        <td>FECHA INGRESO</td>
        </tr>
        </thead>
        <Tbody>
            {% for aux in listaProductos %}
                        <tr>
                            <td>{{ aux.codigo }}</td>
                            <td>{{ aux.nombre }}</td>
                            <td>{{ aux.marca }}</td>
                            <td>{{ aux.precio }}</td>
                            <td>{{ aux.stock }}</td>
                            <td>{{ aux.descripcion }}</td>
                            <td>{{ aux.tipo }}</td>
                            <td><img src="{{ aux.imagen.url }}" style="width: 50px;"></td>
                            <td>{{ aux.created_at }}</td>
                            <td>
                                <a href="{% url 'modificar_producto' aux.codigo %}" class="btn btn-info">Modificar</a>
                                {% if perms.app.delete_producto %}
                                <a onclick="deleteProducto({{aux.codigo}})"" class="btn red darken-3">Eliminar</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
        </tbody>
    </table>


 </div>

    
 
</div>


{% endblock %}

app/templates/app/producto/modificar_producto.html
{% extends 'app/producto/baseprod.html' %}
{% load static %}
{% load crispy_forms_tags %}




{% block contenidouser %}


<div class="container">
  <h4 class="text-center teal lighten-4" style="font-family: Arial, Helvetica, sans-serif;"> Listar Productos</h4>
<div  class="m-5 teal lighten-4">
  <script src="{% static 'app/js/prueba.js'%}"></script>
  <form action="" method="POST" class="m-5" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form|crispy }}
    </table>
    <input type="submit" class="btn mt-5" value="Modificar">
  </form>

  {{ mensaje }}
</div>
</div>

{% endblock %}
{% block css %}

{% if messages %}
                    {% for msj in messages %}
                        <script>
                            Swal.fire({
                                title: 'Guardado!',
                                text: '{{ msj }}',
                                icon: 'success',
                                showConfirmButton: false,
                                timer: 2000
                            });
                        </script>
                    {% endfor %}
                {% endif %}
{% endblock %}

app/templates/app/producto/productos-api.html
{% extends 'app/user/baseuser.html' %}
{% load static %}
{% block contenidouser %}

<div class="container bg-light text-center">
  <h4 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Productos Api</h4>
  <div class="row text-center">


    {% for aux in listaJson %}

    <div class="col-md-3">
      <div class="card adapt">
        {% if aux.imagen %}
        <img src="{{ aux.imagen }}" class="card-img-top">
        {% else %}
        <img class="card-img-top" src="{% static 'app/img/baberos.jpg' %}" alt="Card image" ||>


        {% endif %}

        <div class="card-body">
          <h4 class="card-title" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"> {{ aux.nombre }}</h4>
          <p class="card-text" style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"> {{ aux.descripcion }}</p>
          <p class="card-text" style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"> Tipo: {{ aux.tipo.tipo }}</p>
          <p class="card-text" style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"> Stock: {{ aux.stock }}</p>

          <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="codigo" id="codigo" value="{{aux.codigo}}">
              <input type="hidden" name="nombre" id="nombre" value="{{aux.nombre}}">
              <input type="hidden" name="marca" ID="marca" value="{{aux.marca}}">
              <input type="hidden" name="pecio" id="precio" value="{{aux.precio}}">
              <input type="hidden" name="descripcion" id="descripcion" value="{{aux.descripcion}}">
              <input type="hidden" name="stock" id="stock" value="{{aux.stock}}">
              <input type="hidden" name="tipo" id="tipo" value="{{aux.TipoProducto.tipo}}">
              <input type="hidden" name="imagen" id="imagen" value="{{aux.imagen}}">
              <input type="hidden" name="created_at" id="created_at" value="{{aux.created_at}}">
              <input type="hidden" name="updated_at" id="updated_at" value="{{aux.updated_at}}">


            <a class="btn btn-primary mt-2"> <i class="fa-solid fa-money-check-dollar right"></i></i>${{ aux.precio }}</a>
            <br>
            <input type="submit" class="btn btn  mt-3" value="carrito">
          </form>

        </div>
      </div>
    </div>

    {% endfor %}

  </div>
</div>
{% endblock %}